name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: g++ -Wall -Wextra -Werror --coverage -o senderExe sender/*.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o receiverExe receiver/receiver.cpp
      
    - name: run
      run: ./senderExe | ./receiverExe
      
    - name: receiver coverage report
      run: gcov -r receiver.cpp
    
    - name: sender coverage report
      run: gcov -r Sendermain.cpp
